language: python
python:
    - "2.7"

install:
#    - pushd package
#    - 'if [ ${TRAVIS_BRANCH} \!= "master" ] && [ -f dev_requirements.txt ]; then
#        pip install --extra-index-url https://testpypi.python.org/pypi -r dev_requirements.txt;
#        python setup.py develop --no-deps;
#      else
#        python setup.py install;
#      fi'
#    - pip install -r test_requirements.txt
#    - popd
    - pip install -r src/requirements.txt
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-package=src tests

after_success:
    - coveralls